site_name: chengwei.github.io
theme:
  name: gitbook
  custom_dir: overrides

nav:
  - 首页: index.md
  - 笔记:
    - 2026-04-13 DualMap 阅读笔记: notes/2026-04-13-dualmap/index.md
  - 论文阅读:
    - RAFT 光流 (ECCV 2020): paper_reading/2003.12039_RAFT_Recurrent_All-Pairs_Field_Transforms_for_Optical_Flow/2003.12039_阅读报告.md
